name: Quality Check

# THE TRIGGER
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# THE WORK
jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # server(temp VM) is empty so checkout the code to VM
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Deps
        run: bun install --frozen-lockfile

      - name: Run Linter
        run: bun run lint

      - name: Check Build
        run: bun run build

